---
# defaults var file for homeassistant role

# location of the config directory
ha_conf_dir: /srv/homeassistant

# The default user
ha_user: homeassistant
ha_group: homeassistant

# homeassistant version to install
ha_version: latest

# homeassistant port for web access
ha_port: 8123

# delay in seconds before go ahead with check homeassistant is running, increase when installation failes or while a slow system or internet connection
ha_check_delay: 25

# create a cron job to delete backups
ha_backup_cron: false

# delete backup after given days
ha_backup_delete_after_days: 7

# keep defined backups files
ha_backup_keepfiles: 3

# default for the python installation
ha_python_release: 3.12.2  # See https://www.python.org/downloads/source/
ha_python_src_dir: /tmp
ha_python_archive: Python-{{ ha_python_release }}.tgz
ha_python_url: https://www.python.org/ftp/python/{{ ha_python_release }}/{{ ha_python_archive }}

# backup directory for existing HA installatation before upgrade virtuel env to new version
ha_backup_existing_installation_dir: /home/{{ ha_user }}

# trigger for ha update
ha_version_update: false

# trigger for python update
ha_python_update: false
